on: push
name: Build and deploy GH Pages

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build website
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
